<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<?php $this->load->view('head');?>
<?php $this->load->view('header');?>
<?php $this->load->view('navbar');?>
<body style="
    background-color: #e2d8da;
   /* margin-left: 105px;
    margin-right: 105px;
    margin-top: 61px;*/
     box-shadow: 5px 5px 40px 5px #888888;">
<div class="container" style="background-color: white;padding: 23px;">
<h2><center>How to Apply for a Small Business Loan</center></h2>
<p>For a small business to get off the ground, or to keep one operating, it must have financing which is often in the form of a business loan. One form of small business financing is debt financing. Small businesses can apply to banks or other financial institutions, like credit unions, for commercial loans. Usually, banks do not make loans to start-ups, but they do make loans to ongoing businesses. These are the major steps you should follow through the loan application process.</p><h3>01 Reason for and Amount of the Business Loan-:</h3><p>It seems obvious that a small business owner would know the reason for and amount of the business loan they need. If the business is a start-up, this is not necessarily true. Owners of start-ups may only be in the process of determining the number of funds they need and why. Business owners, whether the firms are start-ups or existing firms, need to take some time and be able to clearly articulate why they need a business loan and how much they need. Often, businesses may not be able to address the question of how much they need until they prepare their financial statements as part of their business plan.</p><h3>02 Visit Your Local SCORE and SBDC Offices-:</h3><p>-: Especially if your business is a start-up, you may want to get some advice and help from experienced executives. If you have a chapter of SCORE in your area, they are a wonderful and free source of advice and help. SCORE is a non-profit, volunteer group of retired business executives. If you don't have a local chapter, you can get online advice and online counseling. You may also have a local chapter of the Small Business Development Center (SBDC), particularly if you have a nearby university. The SBDC is part of the small Business Administration (SBA) and exists to help existing and new small business. It will help small business owners with the application process for a small business loan.</p>
<h3>03 Review Your Credit History and Credit Score-:</h3><p>If your business is a start-up or less than three years old, your personal credit history will be evaluated as     well as your business credit history. Before you apply for a small business loan, take some time to get your personal credit history in order. Request your credit report from each of the major credit reporting agencies. Review these credit reports. If you see any errors on your credit reports, write the agency a letter and detail the error and ask for it to be fixed. If there is an error that the agency will not fix, file a credit dispute report. Check on your credit score. A credit score of about 700 is very good and significantly increases your chance of being approved for a loan.</p><h3>04Start Reviewing Your Borrowing Options-:</h3><p>Look at the commercial banks available to you. Don't just go to the large, national commercial banks. You may have a better chance for a loan at the smaller regional commercial banks. Other non-bank institutions might be options for you such as credit unions. If you are a member of a local credit union, talk to the loan officer there about your need for a small business loan. If they make such loans, pick up a loan application there as well. There are other options such as microfinance loans that make loans to startups. If one lender turns you down, another may say yes to the same loan application so keep trying.</p><h3>05Prepare Your Business Plan-:</h3><p>This may be your most important step. In order to get a small business loan from just about any lender, you have to prepare a good business plan. In fact, until you have a good business plan, chances are you won't even know how much money you need or how fast you can repay it. The business plan is in addition to the loan application required by the financial institution. Business plans consist of many parts. A good business plan will have several years of past and project financial statements for your business. It will include a statement of collateral or the type and value of assets you will use to secure the loan. You will need to include an analysis of the market your business will serve as well as a statement of your own experience.</p>
<h3>06 Plan a Presentation and Make the Appointment-:</h3><p>In order for the loan officer at your financial institution to give your application for a small business loan a second look, you have to make it compelling. Prepare a presentation of your business plan and application for your loan officer. Put together a professional package to hand to your loan officer with a narrative plus any financial statements, spreadsheets, charts, and graphs necessary. Be sure and include an Executive Summary. Many loan officers read the Executive summary first and decide whether they are interested based on that. Make an appointment with your loan officer and request enough time to do a short presentation, with visual aids, based on your business plan. Be concise, succinct, and organized.</p>

</div><br><br>
<?php $this->load->view('footer');?>


</body>
</html>